linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - gofmt
    - revive
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - varcheck
    - vet
    - vetshadow
    - errcheck
    - govet
    - typecheck
    - gocritic

run:

  # timeout for analysis
  timeout: 5m

issues:

  # List of regexps of issue texts to exclude
  exclude:
    - "comment on"
    - "error should be the last"
    - "should have comment"
